config/routes.rb
Rails.application.routes.draw do
  resources :speeds
  resources :traffics

end

app/models/speed.rb
class Speed < ActiveRecord::Base
end

app/models/traffic.rb
class Traffic < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/speeds_controller.rb
class SpeedsController < ApplicationController
  before_action :set_speed, only: [:show, :edit, :update, :destroy]

  # GET /speeds
  # GET /speeds.json
  def index
    @speeds = Speed.all
  end

  # GET /speeds/1
  # GET /speeds/1.json
  def show
  end

  # GET /speeds/new
  def new
    @speed = Speed.new
  end

  # GET /speeds/1/edit
  def edit
  end

  # POST /speeds
  # POST /speeds.json
  def create
    speed_txt = params[:speed_txt]
    
    down = speed_txt.match(/(\d+\.\d+).*(\d+\.\d+)/)[1]
    up   = speed_txt.match(/(\d+\.\d+).*(\d+\.\d+)/)[2]

    @speed = Speed.new(speed_params)
    @speed.down = down
    @speed.up   = up

    respond_to do |format|
      if @speed.save
        @speeds = Speed.all 
        format.html { render "index", notice: 'Speed was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @speed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speeds/1
  # PATCH/PUT /speeds/1.json
  def update
    respond_to do |format|
      if @speed.update(speed_params)
        format.html { redirect_to @speed, notice: 'Speed was successfully updated.' }
        format.json { render :show, status: :ok, location: @speed }
      else
        format.html { render :edit }
        format.json { render json: @speed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speeds/1
  # DELETE /speeds/1.json
  def destroy
    @speed.destroy
    respond_to do |format|
      format.html { redirect_to speeds_url, notice: 'Speed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speed
      @speed = Speed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speed_params
      params.require(:speed).permit(:date, :time, :down, :up, :rem)
    end
end

app/controllers/traffics_controller.rb
class TrafficsController < ApplicationController
  before_action :set_traffic, only: [:show, :edit, :update, :destroy]
  
  # GET /traffics
  # GET /traffics.json
  def index
    @traffics = Traffic.all
  end

  # GET /traffics/1
  # GET /traffics/1.json
  def show
    
  end

  # GET /traffics/new
  def new
    @traffic = Traffic.new
  end

  # GET /traffics/1/edit
  def edit
  end

  require 'csv'
  # POST /traffics
  # POST /traffics.json
  def create
    data = "date,r,s\r\n"+params[:data]
    csv = CSV.new(data, :headers => true, :header_converters => :symbol, :converters => :all)

    h = csv.to_a.map {|row| row.to_hash }

    h.each do |e|
      t = Traffic.find_by date:e[:date]
      if t!=nil 
        t.delete 
      end
      Traffic.create(e)
    end

    @traffics = Traffic.all
    render "index"
  end

  # PATCH/PUT /traffics/1
  # PATCH/PUT /traffics/1.json
  def update
    respond_to do |format|
      if @traffic.update(traffic_params)
        format.html { redirect_to @traffic, notice: 'Traffic was successfully updated.' }
        format.json { render :show, status: :ok, location: @traffic }
      else
        format.html { render :edit }
        format.json { render json: @traffic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /traffics/1
  # DELETE /traffics/1.json
  def destroy
    @traffic.destroy
    respond_to do |format|
      format.html { redirect_to traffics_url, notice: 'Traffic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_traffic
      @traffic = Traffic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def traffic_params
      params.require(:traffic).permit(:date, :r, :s)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speeds_helper.rb
module SpeedsHelper
end

app/helpers/traffics_helper.rb
module TrafficsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Traff</title>
<!-- css3 icon -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/speeds/_form.html.erb
<%= form_for(@speed) do |f| %>
  <% if @speed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speed.errors.count, "error") %> prohibited this speed from being saved:</h2>

      <ul>
      <% @speed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>

  <div class="field">
    <%= label_tag "speed_txt" %><br>
    <%= text_field_tag "speed_txt", "", :autofocus=>true%>
  </div>

  <div class="field">
    <%= f.label :rem %><br>
    <%= f.text_field :rem %>
  </div>

<!--
  <div class="field">
    <%= f.label :down %><br>
    <%= f.text_field :down %>
  </div>
  <div class="field">
    <%= f.label :up %><br>
    <%= f.text_field :up %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speeds/edit.html.erb
<h1>Editing Speed</h1>

<%= render 'form' %>

<%= link_to 'Show', @speed %> |
<%= link_to 'Back', speeds_path %>

app/views/speeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Speeds</h1>

<table class="data">
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Down</th>
      <th>Up</th>
      <th>Rem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @speeds.each do |speed| %>
      <tr>
        <td class='date'><%= speed.date.strftime("%m/%d/%Y")%></td>
        <td class='date'><%= speed.time.strftime("%I:%M%p")%></td>
        <td class='num'><%= speed.down %>Mbps</td>
        <td class='num'><%= speed.up %>Mbps</td>
        <td ><%= speed.rem %></td>
        <td class="control"><%= link_to  speed do %><span class="glyphicon glyphicon-eye-open"></span><% end %></td>
        <td class="control"><%= link_to  edit_speed_path(speed) do %><span class="glyphicon glyphicon-pencil"></span><% end %></td>
        <td class="control"><%= link_to  speed, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-trash"></span><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Speed', new_speed_path %>

app/views/speeds/new.html.erb
<h1>New Speed</h1>

<%= render 'form' %>

<%= link_to 'Back', speeds_path %>

app/views/speeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @speed.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @speed.time %>
</p>

<p>
  <strong>Down:</strong>
  <%= @speed.down %>
</p>

<p>
  <strong>Up:</strong>
  <%= @speed.up %>
</p>

<%= link_to 'Edit', edit_speed_path(@speed) %> |
<%= link_to 'Back', speeds_path %>

app/views/traffics/_form.html.erb
<%= form_for(@traffic) do |f| %>
  <% if @traffic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@traffic.errors.count, "error") %> prohibited this traffic from being saved:</h2>

      <ul>
      <% @traffic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :r %><br>
    <%= f.number_field :r %>
  </div>
  <div class="field">
    <%= f.label :s %><br>
    <%= f.number_field :s %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/traffics/edit.html.erb
<h1>Editing Traffic</h1>

<%= render 'form' %>

<%= link_to 'Show', @traffic %> |
<%= link_to 'Back', traffics_path %>

app/views/traffics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Traffics</h1>

<table class="data">
  <thead>
    <tr>
      <th>Date</th>
      <th>R</th>
      <th></th>
      <th>S</th>
      <th></th>
      <th>Total</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @traffics.each do |traffic| %>
      <tr>
        <td class='date'><%= traffic.date %></td>
        <td class='num'><%= number_with_precision traffic.r, precision:2 %>GB</td>
        <td class='graph'> <meter value="<%=(traffic.r/20)%>" style="width:100px"></meter> </td>
        <td class='num'><%= number_with_precision traffic.s, precision:2 %>GB</td>
        <td class='graph'> <meter value="<%=(traffic.s/20)%>" style="width:100px"></meter> </td>
        <td class='num'><%= number_with_precision traffic.s+traffic.r, precision:2 %>GB</td>
        <td class='graph'> <meter value="<%=((traffic.s+traffic.r)/20)%>" style="width:100px"></meter> </td>
        <td class="control"><%= link_to  traffic do %><span class="glyphicon glyphicon-eye-open"></span><% end %></td>
        <td class="control"><%= link_to  edit_traffic_path(traffic) do %><span class="glyphicon glyphicon-pencil"></span><% end %></td>
        <td class="control"><%= link_to  traffic, method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-trash"></span><% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Traffic', new_traffic_path %>

app/views/traffics/new.html.erb
<h1>New Traffic</h1>


<%= form_tag(action:"create") do %>
  <%= text_area_tag "data","", :rows=>20, :cols=>50 %><br/>
  <%= submit_tag "SEND" %>
<% end %>


<%= link_to 'Back', traffics_path %>

app/views/traffics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @traffic.date %>
</p>

<p>
  <strong>R:</strong>
  <%= @traffic.r %>
</p>

<p>
  <strong>S:</strong>
  <%= @traffic.s %>
</p>

<%= link_to 'Edit', edit_traffic_path(@traffic) %> |
<%= link_to 'Back', traffics_path %>